// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 7T82rs8ypY1wyRtbq2WyBY
// Component: ZCnCrvBpaJY6

import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";
import { useRouter } from "next/router";

import {
  Flex as Flex__,
  MultiChoiceArg,
  PlasmicDataSourceContextProvider as PlasmicDataSourceContextProvider__,
  PlasmicIcon as PlasmicIcon__,
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  PlasmicPageGuard as PlasmicPageGuard__,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  Stack as Stack__,
  StrictProps,
  Trans as Trans__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  generateOnMutateForSpec,
  generateStateOnChangeProp,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  get as $stateGet,
  hasVariant,
  initializeCodeComponentStates,
  initializePlasmicStates,
  makeFragment,
  omit,
  pick,
  renderPlasmicSlot,
  set as $stateSet,
  useCurrentUser,
  useDollarState,
  usePlasmicTranslator,
  useTrigger,
  wrapWithClassName
} from "@plasmicapp/react-web";
import {
  DataCtxReader as DataCtxReader__,
  useDataEnv,
  useGlobalActions
} from "@plasmicapp/react-web/lib/host";

import Button2 from "../../Button2"; // plasmic-import: CDCexgZSPKC3/component

import "@plasmicapp/react-web/lib/plasmic.css";

import plasmic_antd_5_hostless_css from "../antd_5_hostless/plasmic.module.css"; // plasmic-import: ohDidvG9XsCeFumugENU3J/projectcss
import projectcss from "./plasmic.module.css"; // plasmic-import: 7T82rs8ypY1wyRtbq2WyBY/projectcss
import sty from "./PlasmicSelectfunction.module.css"; // plasmic-import: ZCnCrvBpaJY6/css

import ChecksvgIcon from "./icons/PlasmicIcon__Checksvg"; // plasmic-import: WWciTFaavqMj/icon
import Icon38Icon from "./icons/PlasmicIcon__Icon38"; // plasmic-import: lq3Ujgm15KtO/icon

createPlasmicElementProxy;

export type PlasmicSelectfunction__VariantMembers = {};
export type PlasmicSelectfunction__VariantsArgs = {};
type VariantPropType = keyof PlasmicSelectfunction__VariantsArgs;
export const PlasmicSelectfunction__VariantProps = new Array<VariantPropType>();

export type PlasmicSelectfunction__ArgsType = {};
type ArgPropType = keyof PlasmicSelectfunction__ArgsType;
export const PlasmicSelectfunction__ArgProps = new Array<ArgPropType>();

export type PlasmicSelectfunction__OverridesType = {
  root?: Flex__<"div">;
};

export interface DefaultSelectfunctionProps {}

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicSelectfunction__RenderFunc(props: {
  variants: PlasmicSelectfunction__VariantsArgs;
  args: PlasmicSelectfunction__ArgsType;
  overrides: PlasmicSelectfunction__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(() => Object.assign({}, props.args), [props.args]);

  const $props = {
    ...args,
    ...variants
  };

  const __nextRouter = useNextRouter();
  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const currentUser = useCurrentUser?.() || {};

  return (
    <React.Fragment>
      <Head></Head>

      <style>{`
        body {
          margin: 0;
        }
      `}</style>

      <div className={projectcss.plasmic_page_wrapper}>
        <div
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            projectcss.all,
            projectcss.root_reset,
            projectcss.plasmic_default_styles,
            projectcss.plasmic_mixins,
            projectcss.plasmic_tokens,
            plasmic_antd_5_hostless_css.plasmic_tokens,
            sty.root
          )}
        >
          <Button2
            className={classNames("__wab_instance", sty.button2___3Dxcb)}
            color={"green"}
          >
            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__o1Djv
              )}
            >
              {"\u5ea6\u6570\u81ea\u6d4b"}
            </div>
          </Button2>
          <Button2
            className={classNames("__wab_instance", sty.button2__jrwBx)}
            color={"green"}
          >
            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__j2QIu
              )}
            >
              {"\u62a5\u9500\u540e\u8d39\u7528\u6d4b\u7b97"}
            </div>
          </Button2>
        </div>
      </div>
    </React.Fragment>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: ["root"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  root: "div";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicSelectfunction__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicSelectfunction__VariantsArgs;
    args?: PlasmicSelectfunction__ArgsType;
    overrides?: NodeOverridesType<T>;
  } & Omit<PlasmicSelectfunction__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    /* Specify args directly as props*/ Omit<
      PlasmicSelectfunction__ArgsType,
      ReservedPropsType
    > &
    /* Specify overrides for each element directly as props*/ Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    /* Specify props for the root element*/ Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicSelectfunction__ArgProps,
          internalVariantPropNames: PlasmicSelectfunction__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicSelectfunction__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicSelectfunction";
  } else {
    func.displayName = `PlasmicSelectfunction.${nodeName}`;
  }
  return func;
}

export const PlasmicSelectfunction = Object.assign(
  // Top-level PlasmicSelectfunction renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements

    // Metadata about props expected for PlasmicSelectfunction
    internalVariantProps: PlasmicSelectfunction__VariantProps,
    internalArgProps: PlasmicSelectfunction__ArgProps,

    // Page metadata
    pageMetadata: {
      title: "",
      description: "",
      ogImageSrc: "",
      canonical: ""
    }
  }
);

export default PlasmicSelectfunction;
/* prettier-ignore-end */
